import React, { useState, useEffect } from 'react';
import { UploadCloud, Play, User as UserIcon } from 'lucide-react';
import { googleSignIn } from '../lib/auth';
import { uploadToYouTube } from '../lib/youtube';
import type { User } from 'firebase/auth';
import { RenderJob } from '../types';
import { YTAccount } from './YouTubeAccountsTab';

export function YouTubeUploader({ job }: { job: RenderJob }) {
  const [accounts, setAccounts] = useState<YTAccount[]>([]);
  const [token, setToken] = useState<string | null>(null);
  const [isUploading, setIsUploading] = useState(false);
  const [progress, setProgress] = useState(0);
  const [youtubeUrl, setYoutubeUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
     try {
       const stored = localStorage.getItem('youtubeAccounts');
       if (stored) {
          const parsed = JSON.parse(stored);
          setAccounts(parsed);
          if (parsed && parsed.length > 0) {
             setToken(parsed[0].token);
          }
       }
     } catch(e) {}
  }, []);

  const handleLogin = async () => {
    try {
      setError(null);
      const res = await googleSignIn();
      if (res) {
        setToken(res.accessToken);
      }
    } catch (e: any) {
      if(e.code === 'auth/unauthorized-domain') {
          setError('Domain unauthorized by Firebase.');
      } else {
          setError(e.message || 'Login failed');
      }
    }
  };

  const handleUpload = async () => {
    if (!token) return handleLogin();
    if (!job.backendId) {
      setError('Job ID is missing.');
      return;
    }
    
    try {
      setIsUploading(true);
      setError(null);
      setProgress(50); // Just a generic progress indicator since we shifted it to backend

      const title = job.config.name || 'My AI Studio Rendered Video';
      const description = 'Generated by Trisha Video Engine';

      let res: Response | undefined;
      let ytRetries = 3;
      while (ytRetries > 0) {
         res = await fetch(`/api/jobs/${job.backendId}/youtube`, {
            method: 'POST',
            credentials: 'same-origin',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ token, title, description })
         });
         if (res.url && res.url.includes('cookie_check')) {
            const iframe = document.createElement('iframe');
            iframe.src = res.url;
            iframe.style.display = 'none';
            document.body.appendChild(iframe);
            await new Promise(r => setTimeout(r, 3000));
            document.body.removeChild(iframe);
            ytRetries--;
            continue;
         }
         break;
      }
      
      if (!res) throw new Error('Failed to start youtube upload');
      if (!res.ok) {
         let errorText = 'Upload failed';
         try {
           const text = await res.text();
           const data = JSON.parse(text);
           errorText = data.error || errorText;
         } catch(e) {}
         throw new Error(errorText);
      }
      
      let resData;
      try {
        const text = await res.text();
        resData = JSON.parse(text);
      } catch(e) {
        throw new Error("Invalid response format from youtube upload");
      }
      const { url } = resData;
      setProgress(100);
      setYoutubeUrl(url);
    } catch (e: any) {
      setError(e.message || 'Upload failed');
    } finally {
      setIsUploading(false);
    }
  };

  if (youtubeUrl) {
    return (
      <a 
        href={youtubeUrl} target="_blank" rel="noreferrer"
        className="flex-1 flex items-center justify-center gap-1 bg-green-500/10 hover:bg-green-500/20 text-green-400 py-1.5 rounded text-xs font-medium transition-colors"
      >
        <Play className="w-4 h-4" /> Watch on YouTube
      </a>
    );
  }

  return (
    <div className="flex-1 flex flex-col gap-2">
      {isUploading ? (
        <div className="w-full bg-zinc-900 rounded-full h-1.5 overflow-hidden">
           <div className="bg-red-500 h-full transition-all duration-300" style={{ width: `${progress}%` }} />
           <div className="text-[10px] text-zinc-400 mt-1 text-center">Uploading... {progress}%</div>
        </div>
      ) : token ? (
        <button 
          onClick={handleUpload}
          className="w-full h-full flex items-center justify-center gap-1 bg-red-500/10 hover:bg-red-500/20 text-red-500 py-1.5 rounded text-xs font-medium transition-colors"
        >
          <UploadCloud className="w-4 h-4" /> 
          Upload to YouTube
        </button>
      ) : (
        <button className="gsi-material-button w-full h-full flex items-center justify-center bg-white text-zinc-900 rounded py-1" onClick={handleLogin}>
          <div className="gsi-material-button-state"></div>
          <div className="gsi-material-button-content-wrapper flex items-center justify-center gap-2">
            <div className="gsi-material-button-icon w-4 h-4">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" xmlnsXlink="http://www.w3.org/1999/xlink" style={{display: 'block'}}>
                <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
                <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
                <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
                <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
                <path fill="none" d="M0 0h48v48H0z"></path>
              </svg>
            </div>
            <span className="gsi-material-button-contents text-xs font-medium">Sign in</span>
            <span style={{display: 'none'}}>Sign in with Google</span>
          </div>
        </button>
      )}
      {error && <div className="text-[10px] text-red-400 text-center">{error}</div>}
    </div>
  );
}
